CREATE DATABASE IF NOT EXISTS db_main;
CREATE DATABASE IF NOT EXISTS db_alm;
CREATE DATABASE IF NOT EXISTS db_bcn;
CREATE DATABASE IF NOT EXISTS db_bcnalm;
CREATE DATABASE IF NOT EXISTS db_vlc;
CREATE DATABASE IF NOT EXISTS db_wfs1;
CREATE DATABASE IF NOT EXISTS db_wfs1alm;
CREATE DATABASE IF NOT EXISTS db_wfs2;
CREATE DATABASE IF NOT EXISTS db_wfs2alm;
CREATE DATABASE IF NOT EXISTS db_wfs3;
CREATE DATABASE IF NOT EXISTS db_wfs3alm;

CREATE USER IF NOT EXISTS 'app_user'@'%' IDENTIFIED BY 'password_app_segura';
GRANT ALL PRIVILEGES ON *.* TO 'app_user'@'%';
FLUSH PRIVILEGES;
